import { hash, type Call } from "starknet";

const STARK_PRIME = (1n << 251n) + 17n * (1n << 192n) + 1n;
const MAX_OUTSIDE_WINDOW_SECONDS = 301n;

function felt(value: string, label: string): bigint {
  let parsed: bigint;
  try {
    parsed = BigInt(value);
  } catch {
    throw new Error(`${label} is not a felt.`);
  }
  if (parsed < 0n || parsed >= STARK_PRIME) {
    throw new Error(`${label} is outside the Starknet field.`);
  }
  return parsed;
}

function sameFelt(actual: string, expected: string, label: string): void {
  if (felt(actual, label) !== felt(expected, `Expected ${label.toLowerCase()}`)) {
    throw new Error(`${label} was substituted.`);
  }
}

function boundedLength(value: string, remaining: number, label: string): number {
  const parsed = felt(value, label);
  if (parsed > BigInt(Number.MAX_SAFE_INTEGER) || parsed > BigInt(remaining)) {
    throw new Error(`${label} exceeds the outside authorization calldata.`);
  }
  return Number(parsed);
}

/**
 * Parses the exact SNIP-9 V2 wire shape generated by Starknet.js and proves
 * that it authorizes only the already-validated PAYO policy call. This check
 * runs both before simulation and again after durable recovery, closing the
 * simulate-one-call/sign-another TOCTOU boundary.
 */
export function assertDirectPrivacyOutsideCall(input: {
  outsideCall: Pick<Call, "contractAddress" | "entrypoint" | "calldata">;
  policyCall: Pick<Call, "contractAddress" | "entrypoint" | "calldata">;
  relayerAddress: string;
  proofValidAfterUnix: string;
  proofValidBeforeUnix: string;
  currentBlockTimestamp?: number;
}): void {
  const { outsideCall, policyCall } = input;
  if (outsideCall.entrypoint !== "execute_from_outside_v2") {
    throw new Error("The outside authorization selector was substituted.");
  }
  if (policyCall.entrypoint !== "execute_policy_intent") {
    throw new Error("The embedded PAYO policy selector was substituted.");
  }
  sameFelt(outsideCall.contractAddress, policyCall.contractAddress, "Policy account");
  if (!Array.isArray(outsideCall.calldata) || !Array.isArray(policyCall.calldata)) {
    throw new Error("The outside authorization calldata is not flattened.");
  }

  const encoded = outsideCall.calldata.map(String);
  const expectedPolicyCalldata = policyCall.calldata.map(String);
  let cursor = 0;
  const take = (label: string): string => {
    const value = encoded[cursor];
    if (value === undefined) throw new Error(`The outside authorization is missing ${label}.`);
    cursor += 1;
    felt(value, label);
    return value;
  };

  sameFelt(take("caller"), input.relayerAddress, "Outside caller");
  take("outside nonce");
  const executeAfter = felt(take("execute after"), "Execute after");
  const executeBefore = felt(take("execute before"), "Execute before");
  const proofValidAfter = felt(input.proofValidAfterUnix, "Proof valid after");
  const proofValidBefore = felt(input.proofValidBeforeUnix, "Proof valid before");
  if (
    executeAfter < proofValidAfter
    || executeBefore > proofValidBefore
    || executeAfter >= executeBefore
    || executeBefore - executeAfter > MAX_OUTSIDE_WINDOW_SECONDS
  ) {
    throw new Error("The outside authorization has an invalid or over-broad time window.");
  }
  if (input.currentBlockTimestamp !== undefined) {
    const now = BigInt(input.currentBlockTimestamp);
    if (executeAfter >= now || now >= executeBefore || now < proofValidAfter || now >= proofValidBefore) {
      throw new Error("The outside authorization is not valid at the current accepted block.");
    }
  }

  const callCount = boundedLength(take("call count"), encoded.length - cursor, "Call count");
  if (callCount !== 1) throw new Error("The outside authorization must contain exactly one call.");
  sameFelt(take("call target"), policyCall.contractAddress, "Embedded policy account");
  sameFelt(
    take("call selector"),
    hash.getSelectorFromName("execute_policy_intent"),
    "Embedded policy selector",
  );
  const calldataLength = boundedLength(
    take("policy calldata length"),
    encoded.length - cursor,
    "Policy calldata length",
  );
  if (calldataLength !== expectedPolicyCalldata.length) {
    throw new Error("The embedded policy calldata length was substituted.");
  }
  for (let index = 0; index < calldataLength; index += 1) {
    sameFelt(take(`policy calldata ${index}`), expectedPolicyCalldata[index], `Policy calldata ${index}`);
  }
  const signatureLength = boundedLength(
    take("signature length"),
    encoded.length - cursor,
    "Signature length",
  );
  if (signatureLength !== 2) throw new Error("The session signature must contain exactly two felts.");
  take("signature r");
  take("signature s");
  if (cursor !== encoded.length) throw new Error("The outside authorization contains trailing calldata.");
}
