[package]
name = "vesting_devnet_harness"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.1"

[cairo]
sierra-replace-ids = false

[lib]

[[target.starknet-contract]]
casm = true
