[package]
name = "payo_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.1"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.57.0" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"
